### PR TITLE
Update mkdocs-contributor-guide to include mike dependency

### PR DESCRIPTION
**Pull request by AlexandreBrown**
This PR improves the documentation for the contributors.
I wanted to contribute to kserve/website and I could not get the webiste running locally with the proposed documentation.
We need to install `mike` in order to make `mkdocs serve` work.

### CODE REVIEW

**Comment by yuzisun** [comment]
@AlexandreBrown Thanks for the fix! Can you help sign off the commit with the [instruction](https://github.com/kserve/website/pull/66/checks?check_run_id=4638532316) ?

**Comment by AlexandreBrown** [comment]
@yuzisun Done

**Comment by yuzisun** [comment]
Thanks @AlexandreBrown !

/lgtm
/approve

**Pull request merged**
