### PR TITLE
Add Striveworks to adopter list

### PR DESCRIPTION
**Pull request by JakeNeyer**
This PR will add Striveworks to the list of kserve adopters

## Proposed Changes 

- add Striveworks to adopters list

### CODE REVIEW

**Comment by yuzisun** [comment]
thanks @JakeNeyer !! 

Do you also want to add the logo to the [main page](https://github.com/kserve/website/blob/main/overrides/home.html#L250) ?

**Comment by JakeNeyer** [comment]
@yuzisun that would be awesome! I'll add that to the PR 🙂

**Comment by yuzisun** [comment]
Thanks @JakeNeyer !! Welcome to the family !

/lgtm
/approve

**Pull request merged**
