### PR TITLE
Update sdk class names

### PR DESCRIPTION
**Pull request by markwinter**
## Proposed Changes 

- Update sdk usage following this PR https://github.com/kserve/kserve/pull/1951

### CODE REVIEW

**Comment by theofpa** [comment]
Thanks @markwinter !

**Comment by yuzisun** [comment]
@theofpa @markwinter We shouldn't merge this yet as KServe SDK 0.8 is not released, can we revert the change?

**Comment by yuzisun** [comment]
Actually, let me check if we can add a new pointer to the latest branch for the master branch doc.

**Comment by markwinter** [comment]
@yuzisun https://github.com/kserve/website/pull/81

**Pull request merged**
