### PR TITLE
add Cars24 to adopters list

### PR DESCRIPTION
**Pull request by swapkh91**
Adding Cars24 to the list of adopters

### CODE REVIEW

**Comment by yuzisun** [comment]
@swapkh91 Can you help sign off the commit?

**Comment by swapkh91** [comment]
@yuzisun just checked the main page, can I add the logo too?

**Comment by swapkh91** [comment]
@yuzisun added the svg logo

**Comment by yuzisun** [comment]
Welcome to the community! @swapkh91 

/lgtm
/approve

**Pull request merged**
