### PR TITLE
Add upstage

### PR DESCRIPTION
**Pull request by JuHyung-Son**
"Fixes #issue-number" or "Add description of the problem this PR solves"

## Proposed Changes 

-
-
-

### CODE REVIEW

**Comment by yuzisun** [comment]
Thanks @JuHyung-Son! Do you also want to add the logo to the main page?

**Comment by JuHyung-Son** [comment]
yes! this is our logo
image

**Comment by yuzisun** [comment]
@JuHyung-Son Can you help add here ?
https://github.com/kserve/website/blob/main/overrides/home.html#L259

**Comment by yuzisun** [comment]
@JuHyung-Son Welcome to the community!

/lgtm
/approve

**Pull request merged**
