### PR TITLE
Updated to include Red Hat

### PR DESCRIPTION
**Pull request by taneem-ibrahim**
"Fixes #issue-number" or "Add description of the problem this PR solves"

## Proposed Changes 

- Updated to include Red Hat as an adopter of kserve
-
-

### CODE REVIEW

**Comment by yuzisun** [comment]
Thanks @taneem-ibrahim ! Do you also want to include the redhat logo on the home page ?

**Comment by taneem-ibrahim** [comment]
> Thanks @taneem-ibrahim ! Do you also want to include the redhat logo on the home page ?

Hi Dan - that'd be awesome. Do you already have the logo? If not do you want it in a specific format? Thank you!

**Comment by yuzisun** [comment]
> > Thanks @taneem-ibrahim ! Do you also want to include the redhat logo on the home page ?
> 
> Hi Dan - that'd be awesome. Do you already have the logo? If not do you want it in a specific format? Thank you!

@taneem-ibrahim Can try the format which fits on the [home page](https://kserve.github.io/website/0.10/)

**Comment by yuzisun** [comment]
@taneem-ibrahim can create a separate PR to add the logo

/lgtm
/approve

**Pull request merged**
